frontend/.gitignore
frontend/README.md
frontend/package-lock.json
frontend/package.json
frontend/public/index.html
frontend/public/manifest.json
frontend/src/App.js
frontend/src/components/MainPage/MainPage.js
frontend/src/components/NavBar/NavBar.js
frontend/src/index.css
frontend/src/index.js
frontend/src/store/errors.js
frontend/src/store/jwt.js
frontend/src/store/session.js
frontend/src/store/store.js

front end built up to session and session errors

Frontend new

---

frontend/src/components/NavBar/NavBar.js

navlogic fixed

---

frontend/package.json
frontend/src/components/NavBar/NavBar.js
frontend/src/components/Routes/Routes.js
frontend/src/components/SessionForms/LoginForm.js
frontend/src/components/SessionForms/SignUpForm.js
frontend/src/store/jwt.js

sign in and up form rendereing

Frontend debug

---

frontend/src/components/HomePage/HomePage.css
frontend/src/components/HomePage/HomePage.js

starting homepage

---

frontend/src/components/SessionForms/LoginForm.js

redirect to home

---

backend/routes/api/tuneups.js
backend/seeders/seeds.js

modified seed file to include tuneups, hosts and connections

added seed file

---

backend/routes/api/tuneups.js
backend/routes/api/users.js
backend/seeders/seeds.js

update routes for tuneups and users so they update correspondingly

Backend connections

---

README.md
backend/routes/api/distance.js
frontend/public/index.html
frontend/src/components/MainPage/MainPage.js

Also cleaned up some console logs in the backend, and minor fixes to readme

Add fontawesome functionality

---

frontend/.gitignore
frontend/src/App.js
frontend/src/components/SessionForms/SignUpForm.js
frontend/src/components/SessionForms/UserUpdateForm.css
frontend/src/components/SessionForms/UserUpdateForm.js
frontend/src/store/session.js
frontend/src/store/users.js

User update form complete. Functionality built. Need more testing with backend engineers IRL.

Frontend usersreducer

---

backend/routes/api/users.js
backend/seeders/seeds.js

Update users location to store just the complete address. Update tune ups to now store complete address and zipcode. Reseed database.

Update user location attributes and reseed

---

frontend/src/components/Map/DistanceCalculator.js
frontend/src/components/Map/UserDistanceToAddress.js

Also fixed a bug with distance calculation

Add user geolocation and distance to target address

---

frontend/src/App.js
frontend/src/components/Discover/Discover.css
frontend/src/components/Discover/Discover.js
frontend/src/components/TuneUp/TuneUp.css
frontend/src/components/TuneUp/TuneUp.js
frontend/src/index.js
frontend/src/store/store.js
frontend/src/store/tuneUps.js
frontend/src/store/users.js
frontend/src/util/dateUtils.js

added functional TuneUp component and discover page that renders ALL tuneups available in DB. just need to add styling

Fix update user

---

frontend/src/components/NavBar/NavBar.css
frontend/src/components/NavBar/NavBar.js
frontend/src/components/SessionForms/UserUpdateForm.css
frontend/src/components/SessionForms/UserUpdateForm.js
frontend/src/components/UserProfilePage/UserProfilePage.css
frontend/src/components/UserProfilePage/UserProfilePage.js

use profile rendering complete

---

backend/routes/api/users.js
frontend/src/App.js
frontend/src/components/HomePage/HomePage.js
frontend/src/components/SearchBar/SearchBar.js
frontend/src/store/search.js
frontend/src/store/store.js

Frontend search

---

frontend/src/components/SessionForms/UserUpdateForm.css
frontend/src/components/SessionForms/UserUpdateForm.js
frontend/src/components/UserProfilePage/UserProfilePage.css

er profile page css styling patch

update form css patch, us

---

frontend/src/components/Discover/Discover.css
frontend/src/components/Discover/Discover.js

fixed scrolling issue on discover page

ready for maps

---

backend/routes/api/users.js
frontend/src/components/Discover/Discover.css
frontend/src/components/Discover/Discover.js
frontend/src/components/Map/MultipleZipcodeMap.js
frontend/src/components/NavBar/NavBar.js
frontend/src/components/SessionForms/UserUpdateForm.js
frontend/src/components/TuneUp/TuneUp.css
frontend/src/components/TuneUp/TuneUp.js
frontend/src/components/UserProfilePage/UserProfilePage.css
frontend/src/components/UserProfilePage/UserProfilePage.js

pushing so you guys have my most up to date code

Tune up styling

---

backend/routes/api/tuneups.js
frontend/src/components/CreateTuneUps/CreateTuneUps.js
frontend/src/store/tuneUps.js

Update tuneup create form to to pass date and status field to back + update backend to pass status and instruments to db when creating tuneup.

Frontend create

---

backend/routes/api/search.js
frontend/src/components/Discover/Discover.css
frontend/src/components/Discover/Discover.js
frontend/src/components/SearchBar/SearchBar.css
frontend/src/components/SearchBar/SearchBar.js

tuneups changing depending on search

search working on discover page

---

frontend/src/components/CreateTuneUps/CreateTuneUps.css
frontend/src/components/CreateTuneUps/CreateTuneUps.js

Also made additional edits to the create tuneup form

Add icons to create tuneup

---

frontend/src/components/Discover/Discover.css
frontend/src/components/Discover/Discover.js
frontend/src/components/SearchBar/SearchBar.css
frontend/src/components/SearchBar/SearchBar.js

upon search when searchbar is empty, all tuneups render

---

frontend/src/components/SessionForms/UserUpdateForm.js

Change states and setStates useState hook back to plural form

Change back to getStates hook

---

frontend/src/components/TuneUp/TuneUp.js
frontend/src/store/tuneUps.js

pushing what I have so far for connections.

Connections

---

backend/routes/api/tuneups.js

Fix join tuneup route with user variable declaration and assignment

Join tuneup

---

frontend/src/components/Discover/Discover.js
frontend/src/components/Map/MultipleZipcodeMap.js
frontend/src/components/SearchBar/SearchBar.js
frontend/src/components/SessionForms/UserUpdateForm.js

Also added minor functionality to search bar, and made a frontend change for address input

Discover map changes on search

---

frontend/src/components/SessionForms/UserUpdateForm.css
frontend/src/components/SessionForms/UserUpdateForm.js
frontend/src/components/UserProfilePage/UserProfilePage.css
frontend/src/components/UserProfilePage/UserProfilePage.js

user able to select more than 1 genre/ styled

Frontend user profile

---

frontend/src/components/SessionForms/UserUpdateForm.js
frontend/src/components/UserProfilePage/UserProfilePage.css

Frontend user update

---

frontend/src/components/CreateTuneUps/CreateTuneUps.css
frontend/src/components/CreateTuneUps/CreateTuneUps.js
frontend/src/components/SessionForms/UserUpdateForm.css
frontend/src/components/SessionForms/UserUpdateForm.js
frontend/src/components/TuneUp/TuneUp.js
frontend/src/components/UserProfilePage/UserProfilePage.js

Fix create tuneup form and update user form date inputs and error validations etc... commit messages provide additional context.

Frontend mudassar

---

frontend/src/components/SessionForms/LoginForm.css
frontend/src/components/SessionForms/LoginForm.js

demo login

---

backend/seeders/seeds.js

Backend seeds

---

frontend/src/components/CreateTuneUps/CreateTuneUps.js

Tune up form address validations enabled

Validations

---

frontend/src/components/SessionForms/UserUpdateForm.js

Fix user update form prefill zip and date

Fix user update form prefill zip and date

---

frontend/src/components/AboutDevs/AboutDevs.css
frontend/src/components/AboutDevs/AboutDevs.js

all styled up and ready to go (maybe)

Styling discover page

---

frontend/src/components/CreateTuneUps/CreateTuneUps.js

Fix create tuneup address trim issue

---

frontend/src/components/Discover/Discover.js
frontend/src/components/HomePage/HomePage.js
frontend/src/components/Map/MultipleZipcodeMap.js

Maps tooltip

---

frontend/src/components/SessionForms/UserUpdateForm.js

redirect to instructions page instead of profile page

---

frontend/src/components/SessionForms/LoginForm.css
frontend/src/components/SessionForms/LoginForm.js
frontend/src/components/SessionForms/SignUpForm.css

errors on signin clears when going to another page, more space between error message and respective input label

Frontend error handling

---

backend/seeders/seeds.js
frontend/src/components/NavBar/NavBar.js
frontend/src/components/SessionForms/SignUpForm.js
frontend/src/components/SessionForms/UserUpdateForm.js
frontend/src/components/UserProfilePage/UserProfilePage.js
frontend/src/store/session.js

Made it so when you're signing up and go to the update form, the view profile drop down does not render

Fix signup view profile bug
